// Test-only data: never imported by the application.
import type { DashboardData, FeedbackRow, Recommendation } from '@/lib/types';
export const feedbackRows: FeedbackRow[] = [
  {
    feedback: {
      id: 1,
      feedback_id: 'TEST-001',
      source: 'test-sheet',
      submitted_at: null,
      rating: null,
      customer_name: null,
      customer_email: null,
      feedback_text: 'The delivery arrived late.',
      processing_status: 'classified',
      created_at: '2026-01-01T00:00:00Z',
    },
    analysis: {
      id: 1,
      feedback_db_id: 1,
      feedback_id: 'TEST-001',
      primary_category: 'Delivery',
      sentiment: 'Negative',
      severity: 'Medium',
      summary: 'Late delivery.',
      is_mixed: false,
      confidence: 0.9,
      requires_review: false,
      analysis_status: 'completed',
      model_used: 'test-model',
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
      aspects: [
        {
          id: 1,
          category: 'Delivery',
          sentiment: 'Negative',
          severity: 'Medium',
          evidence_text: 'delivery arrived late',
        },
      ],
    },
  },
  {
    feedback: {
      id: 2,
      feedback_id: 'TEST-002',
      source: 'test-form',
      submitted_at: null,
      rating: null,
      customer_name: null,
      customer_email: null,
      feedback_text: 'Excellent service, thank you.',
      processing_status: 'pending',
      created_at: '2026-01-01T00:00:00Z',
    },
  },
];
export const dashboard: DashboardData = {
  overview: {
    total_feedback_count: 2,
    trusted_validated_feedback_count: 0,
    records_requiring_human_review: 0,
    rated_feedback_count: 0,
    average_rating: null,
    total_aspect_count: 0,
    source_counts: [],
    recurring_negative_trend_count: 0,
    recurring_positive_pattern_count: 0,
  },
  sentiment: {
    total: 0,
    positive: 0,
    neutral: 0,
    negative: 0,
    mixed: 0,
    positive_percentage: 0,
    neutral_percentage: 0,
    negative_percentage: 0,
    mixed_percentage: 0,
  },
  categories: { trusted_feedback_count: 0, total_aspect_count: 0, categories: [] },
  severity: {
    total: 0,
    low: 0,
    medium: 0,
    high: 0,
    high_severity_negative: 0,
    high_severity_by_category: [],
  },
  trends: { threshold: 3, positive_patterns: [], negative_patterns: [] },
  timeline: { period: 'weekly', points: [] },
  emerging: {
    period: 'weekly',
    current_period_start: null,
    previous_period_start: null,
    minimum_current_count: 3,
    percentage_increase_threshold: 50,
    issues: [],
  },
  cases: [],
};
export const recommendation: Recommendation = {
  id: 1,
  category: 'Delivery',
  priority: 'Medium',
  problem_summary: 'Test evidence reports delays.',
  recommendation: 'Review the reported delays.',
  business_rationale: 'Investigate the supported feedback.',
  evidence_count: 1,
  supporting_feedback_ids: ['TEST-001'],
  requires_management_approval: true,
  approval_status: 'pending',
  confidence: 0.9,
  model_used: 'test-model',
  created_at: '2026-01-01T00:00:00Z',
  updated_at: '2026-01-01T00:00:00Z',
  approval_history: [],
};
